baseURL = "https://communityboats.co.uk"
disableLanguages = []
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
languageName = "En"
paginate = "6"
summaryLength = "10"
theme = "twenty-twenty-hugo"
title = "Community Boats"
[markup.goldmark.renderer]
unsafe = true
[[menu.desktop]]
URL = "contact"
name = "Contact"
weight = 1
[[menu.main]]
URL = "/"
name = "Home"
weight = 1
[[menu.main]]
URL = "about"
name = "About"
weight = 2
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 3
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 4
[[menu.main]]
URL = "sample-page"
name = "Sample Page"
weight = 5
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
author = "Luke Slowen"
description = "Community Boats website"
[params.banner]
heading = "Welcome to the Community Boats blog"
image = "images/james-homans-M0IXYeV3a6s-unsplash.jpg"
[params.blog]
heading = "Here we share news, views and commentary from the cut."
[params.call_to_action]
button_label = "Get in touch"
button_url = "contact"
content = "Canals are all about community - we'd love to hear your stories, views, grumbles... whatever you like!"
enable = true
title = "We'd love to hear from you."
[params.cookies]
enable = true
expire_days = 2
[params.favicon]
favicon = "images/favicon.png"
[params.footer]
address = "Middle Lock, Hillmorton, Rugby UK"
content = "Mostly the ramblings of Baz Slowen, UK boatman and community leader of 50+ years."
copyright = "Copyright &copy; 2022 communityboats.co.uk"
hours = ""
title = "About This Site"
[params.gallery]
enable = false
[[params.gallery.gallery_item]]
image = "images/2020-square-2.png"
[[params.gallery.gallery_item]]
image = "images/2020-square-1.png"
[params.social]
email = "info@communityboats.co.uk"
facebook = "https://www.facebook.com/baz.slowen"
instagram = ""
linkedin = ""
twitter = ""
yelp = ""
[taxonomies]
author = "author"
category = "categories"
tag = "tags"
